### ISSUE TITLE
Question: TG_OWT_BUILD_AUDIO_BACKENDS

### ISSUE THREAD

**Issue by mid-kid** [desktop-app/tg_owt#63]
What is the meaning of this flag? Aside from what it says on the tin, I have no idea what they're used for, nor why you'd want them.
Can alsa and pulseaudio be enabled separately, like in libtgvoip?

**Comment by mid-kid** [comment]
https://github.com/desktop-app/tg_owt/blob/master/src/modules/audio_device/audio_device_impl.cc#L243
Apparently you can't enable pulse without alsa, so that's something to keep in mind.

**Comment by ilya-fedin** [comment]
> What is the meaning of this flag?

tdesktop doesn't use these audio backends, it uses openal since these internal audio backends are provided by google only for demo purposes and have a lot of problems when you're going to use them on real systems (e.g. lack of >96Ghz support on Windows, etc, etc). But someone started to use tg_owt for their own purposes and requested preston to add a flag to build them.

**Comment by mid-kid** [comment]
I see! I was afraid it was going to be necessary for some screen recording things or whatnot. I had ended up creating [a few patches](https://github.com/gentoo/gentoo/tree/master/media-libs/tg_owt/files) to disable pulseaudio separately, though I guess those might end up being useful anyway if some other app decides to use this...

**Comment by ilya-fedin** [comment]
Rename all the options to TG_OWT_DISABLE_{X11_INTEGRATION,WAYLAND_INTEGRATION,ALSA,PULSEAUDIO}
(WAYLAND_INTEGRATION is for pipewire)

set_allow_pipewire should be fixed on tgcalls side, it should check for `if defined WEBRTC_USE_PIPEWIRE` as well

**Comment by ilya-fedin** [comment]
oh, tg_owt already uses USE scheme. It's ok as-is, then.

**Comment by ilya-fedin** [comment]
but TG_OWT_USE_PULSEAUDIO, not TG_OWT_BUILD_PULSE_BACKEND.
